In [14]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
one_hot("amazing restaurant",30)

[28, 23]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[20, 13], [28, 23], [16, 27], [25, 25, 25], [28, 4, 4], [9, 13], [14, 4, 17], [27, 13], [27, 3], [21, 8]]


In [15]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[20 13  0]
 [28 23  0]
 [16 27  0]
 [25 25 25]
 [28  4  4]
 [ 9 13  0]
 [14  4 17]
 [27 13  0]
 [27  3  0]
 [21  8  0]]


In [16]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [17]:
X = padded_reviews
y = sentiment

In [18]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 4)              120       
_________________________________________________________________
flatten_1 (Flatten)          (None, 12)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 13        
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________
None


In [19]:

model.fit(X, y, epochs=50, verbose=0)

In [20]:

# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 92ms/step - loss: 0.6417 - accuracy: 0.8000


0.800000011920929

In [10]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [11]:
weights[13]

array([ 0.02178022, -0.05869671, -0.07392105,  0.08119331, -0.07018882],
      dtype=float32)

In [12]:

weights[4]

array([ 0.06268798, -0.00882239,  0.08821599, -0.04740866, -0.10008425],
      dtype=float32)

In [13]:

weights[16]

array([-0.01566044,  0.03056392,  0.03092956, -0.10037196,  0.10023265],
      dtype=float32)